BEGIN;

CREATE ROLE fintech_migrator
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE;

CREATE ROLE fintech_app
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE;

REVOKE ALL PRIVILEGES ON DATABASE fintech_dev FROM PUBLIC;

GRANT CONNECT ON DATABASE fintech_dev
    TO fintech_migrator, fintech_app;

REVOKE ALL PRIVILEGES ON SCHEMA public FROM PUBLIC;

CREATE SCHEMA customers AUTHORIZATION fintech_migrator;

GRANT USAGE ON SCHEMA customers TO fintech_app;

COMMIT;
